# Site Settings
lang: en
title: Rachael Keller World
#tagline: Bulma Clean Theme
#email: your-email@domain.com
description: >- # this means to ignore newlines until "baseurl:"
  A website to host some awesome stuff I find and develop. Just you wait!
baseurl: "" # the subpath of your site, e.g. /blog
url: "r-keller.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: mathrunnergirl
#github_username:  r-keller
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

#paginate: 5
#paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "R Keller"
      layout: post
      image: assets/img/aethel
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

